### ISSUE TITLE
Is this module supposed to be compiled before inclusion?

### ISSUE THREAD

**Issue by stewhouston** [PillowPillow/ng2-webstorage#1]
Pardon me if I've overlooked something fundamental to Angular2 as the module inclusion has given me more trouble than anything thus far. Anyhow, I see the entire source code for the repo is in TypeScript. Given that Angular imports script files in the browser using XHR, do they not ultimately need to be basic JavaScript files?

If the library is intended to be compiled with tsc, I am receiving the following errors when attempting to do so:

```node_modules/ng2-webstorage/lib/app.ts(5,1): error TS2308: Module './decorators' has already exported a member named 'WebStorage'. Consider explicitly re-exporting to resolve the ambiguity.
node_modules/ng2-webstorage/lib/helpers/storageObserver.ts(8,45): error TS2314: Generic type 'EventEmitter<T>' requires 1 type argument(s).
node_modules/ng2-webstorage/lib/interfaces/storage.ts(8,23): error TS2314: Generic type 'EventEmitter<T>' requires 1 type argument(s).
node_modules/ng2-webstorage/lib/services/webStorage.ts(29,29): error TS2314: Generic type 'EventEmitter<T>' requires 1 type argument(s).```

**Comment by PillowPillow** [comment]
Hi, i built this library with webpack in mind so i didn't have a need for a compilation process. I'll add it during the next night for the systemjs users.
btw, thanks for the naming conflict report, i'll fix it with the next commit.

**Comment by PillowPillow** [comment]
The last commit fix the errors and adds a compiled version of the library. If you're using systemjs you simply have to import the ng2-webstorage  in you application via `import {...} from 'ng2-webstorage/index'`.

**Comment by stewhouston** [comment]
Works like a charm. Thanks!
