### ISSUE TITLE
BrowserModule already imported

### ISSUE THREAD

**Issue by Gillardo** [PillowPillow/ng2-webstorage#10]
I have tried using this module in my application, and i get the above error message.

I believe your supposed to import the CommonModule instead of the BrowserModule in your code?

**Comment by PillowPillow** [comment]
Hi
no, the library does't need anything at all, i forgot to remove this dependency before publish. I'll fix it.

**Comment by Gillardo** [comment]
This published to npm yet?

**Comment by PillowPillow** [comment]
yes, why? do you still have the issue?

**Comment by Gillardo** [comment]
no just, asking as will check it shortly, thanks

**Comment by Gillardo** [comment]
Just to let you know, its all fine.. thank you
