### ISSUE TITLE
Migration from v2 to v3

### ISSUE THREAD

**Issue by andrea-corley** [PillowPillow/ng2-webstorage#108]
I'm trying to migrate from v2 version to v3 and I've an error during compilation: 

ERROR in : Can't resolve all parameters for LocalStorageService in /home/tt/Projects/ANGULAR/starter-kit/node_modules/ngx-webstorage/ngx-webstorage.d.ts: (?).

I already changed import in main module to 
NgxWebstorageModule.forRoot() But the issue persist. Do you have some ideas?

**Comment by PillowPillow** [comment]
Hi @andrea-corley , did you see [this issue](https://github.com/PillowPillow/ng2-webstorage/issues/106). It may be related.

**Comment by PillowPillow** [comment]
any news?

**Comment by PillowPillow** [comment]
closing this issue, feel free to open another one if the problem occurs again
