### ISSUE TITLE
"export 'ɵɵdefineInjectable', 'ɵɵinject' was not found in '@angular/core'

### ISSUE THREAD

**Issue by clementlee8** [PillowPillow/ng2-webstorage#110]
WARNING in ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 396:62-80
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 1058:55-73
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 1058:145-153
"export 'ɵɵinject' was not found in '@angular/core'

"@angular/animations": "~7.2.0",
"@angular/common": "~7.2.0",
"@angular/compiler": "~7.2.0",
"@angular/core": "~7.2.0",
"@angular/forms": "~7.2.0",
"@angular/http": "^7.2.15",
"@angular/platform-browser": "~7.2.0",
"@angular/platform-browser-dynamic": "~7.2.0",
"@angular/router": "~7.2.0",
"@ngx-translate/core": "^11.0.1",
"core-js": "^2.5.4",
"ngx-admin-lte": "^2.0.0-beta.11",
"ngx-webstorage": "^4.0.1",
"rxjs": "~6.3.3",
"rxjs-compat": "6.3.3",
"tslib": "^1.9.0",
"zone.js": "~0.8.26"

**Comment by PillowPillow** [comment]
Not a valid issue. closing this.

FYI : https://github.com/PillowPillow/ng2-webstorage/wiki
