### ISSUE TITLE
Don't convert date from string

### ISSUE THREAD

**Issue by johnguzenko** [PillowPillow/ng2-webstorage#118]
When I put any object which contains date field using ngx-webstorage to localstorage and try to get object back, the date field is string.

**Comment by lukaonik** [comment]
This is how it should work. 
whenever you retrieve something from SessionStorage/LocalStorage it's a string type, so it uses JSON.parse() internally to retrieve an object. JSON.parse doesn't have Date type so it becomes a string type.
you have to make it by yourself
