### ISSUE TITLE
LocalStorage decorator arrays

### ISSUE THREAD

**Issue by CarloHagens** [PillowPillow/ng2-webstorage#12]
When using the @LocalStorage() decorator above a property that is an array of objects it doesn't update the localstorage whenever an object in that array changes.

**Comment by PillowPillow** [comment]
Hello, the library is based on accessors so the update triggers only on value change. When you update the inner value of an object or an array, the reference doesn't change and the accessors aren't triggered. There is no trick to solve that issue without dirty check every Xms the content of your array which is a solution that i'll never implement.

To fix your problem you have to trigger the *get* accessor by assign the the bound property to himself (that should be enough) or change your array reference. 

````typescript
import {LocalStorage} from 'ng2-webstorage';

class FooBar {
	
	@LocalStorage('prop')
	myArray;
	
	updateValue() {
		this.myArray.push('foobar');
		this.myArray = this.myArray; // should be enough 
		// this.myArray = [...this.myArray]; change the array reference
	}

}

````

**Comment by CarloHagens** [comment]
Yeah that is the conclusion I came to as well. Was just wondering if this something that was supported or meant to be supported by the decorator.
