### ISSUE TITLE
Error about StrategyIndex when deploy on firebase hosting

### ISSUE THREAD

**Issue by anhnt2899** [PillowPillow/ng2-webstorage#126]
Versions:
 - NgxWebstorage: 5.0.0
 - Angular: 8.2.9

Describe the bug:
- when use comman ngbuild --prod got error about typescript syntax
- When deploy to firebase hosting i got error 'No provider for StrategyIndex'

To Reproduce: 
1. Build product
2. Firebase deploy
3. check error

Screenshots
* when deploy to firebase:
![err1](https://user-images.githubusercontent.com/43347891/75621664-9b489200-5bc9-11ea-9370-6a80d518dcd0.PNG)
*when build product:
![err3](https://user-images.githubusercontent.com/43347891/75621702-42c5c480-5bca-11ea-8cad-e36f471b6a3b.PNG)

**Comment by AsafAgranat** [comment]
I'm getting the same error on app compilation. Meaning that I can't get my app to start anymore..

**Comment by AngularPlayer** [comment]
same here, any solution ?
