### ISSUE TITLE
Error building ngx-webstorage after upgrade to Angular 9.1

### ISSUE THREAD

**Issue by dorje42** [PillowPillow/ng2-webstorage#128]
**Versions (please complete the following information):**
 - NgxWebstorage: 5.0.0
 - Angular: 9.1.0

**Describe the bug**
I updatet my project to Angular 9.1.
When I build my project, I get the following errors:

`
node_modules/ngx-webstorage/lib/core/strategyCache.d.ts:14:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

14     static ɵfac: ɵngcc0.ɵɵFactoryDef<StrategyCacheService>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-webstorage/lib/strategies/localStorage.d.ts:15:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

15     static ɵfac: ɵngcc0.ɵɵFactoryDef<LocalStorageStrategy>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-webstorage/lib/strategies/sessionStorage.d.ts:15:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

15     static ɵfac: ɵngcc0.ɵɵFactoryDef<SessionStorageStrategy>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-webstorage/lib/strategies/inMemory.d.ts:16:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

16     static ɵfac: ɵngcc0.ɵɵFactoryDef<InMemoryStorageStrategy>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-webstorage/lib/services/strategyIndex.d.ts:21:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

21     static ɵfac: ɵngcc0.ɵɵFactoryDef<StrategyIndex>;

`

**Comment by dorje42** [comment]
After removing all node_modules and install it clean again it works.

**Comment by tsanko** [comment]
NgxWebstorage: 6.0.0
Angular: 9.1.12

Compiling ngx-webstorage : module as esm5
Error: Error on worker #3: Error: getInternalNameOfClass() called on a non-ES5 class: expected StrategyCacheService to have an inner class declaration

**Comment by shruti-ahuja** [comment]
> NgxWebstorage: 6.0.0
> Angular: 9.1.12
> 
> Compiling ngx-webstorage : module as esm5
> Error: Error on worker #3: Error: getInternalNameOfClass() called on a non-ES5 class: expected StrategyCacheService to have an inner class declaration

Running into similar issue, any resolve?
