### ISSUE TITLE
Localstorage/sessionstorage clear not working

### ISSUE THREAD

**Issue by CarloHagens** [PillowPillow/ng2-webstorage#13]
As title describes, the clear function on both LocalStorageService and SessionStorageService do not seem to work. I have tried the following for each:

`this.storage.clear('myprop');`
`this.storage.clear();`

**Comment by PillowPillow** [comment]
My unit tests seems to pass, can you provide me more information about the context?

**Comment by CarloHagens** [comment]
After some more testing it seems that I was immediately adding the object again after clearing, which caused the confusion as they were identical. Closing this.
