### ISSUE TITLE
Set expires

### ISSUE THREAD

**Issue by mackelito** [PillowPillow/ng2-webstorage#138]
Would love to see a feature where we can set expires much like on a cookie.. of course we can implement this feature on our own, just thought it would be a nice extra feature for the library :)

**Comment by PillowPillow** [comment]
Hello @mackelito, I never needed it but I agree with you, it could be a good features. Feel free to open a pull request, I'll implement it with joy.

**Comment by mackelito** [comment]
We don't have that need either.. just thought it would be a nice addition.. If I get time over I would take a look at it but not for a few weeks at least :)
