### ISSUE TITLE
Subscribing in template using async pipe

### ISSUE THREAD

**Issue by mackelito** [PillowPillow/ng2-webstorage#139]
I define the Observable as 
```
this.cart$ = this.storage.observe('cart');
```

and then in the template I just subscribe `{{(cart$ | async | json)}}` but I get null.

Note: If I try to fetch the value using a decorator ` @LocalStorage('cart') cart: Cart;`
I see that the property cart does contain what I expect..

**Comment by mackelito** [comment]
Did some more testing...
even if I'm subscribing I don't get an initial value..
```
this.storage.observe('cart').subscribe(e => console.log('e', e));
```
This will only console log the value on an update.. no init value...

**Comment by mackelito** [comment]
Guess it has something to do with filters?
https://github.com/PillowPillow/ng2-webstorage/blob/271d2dda40158d2d543297a3f914a3a3f7183ed0/projects/ngx-webstorage/src/lib/core/templates/asyncStorage.ts#L31

**Comment by mackelito** [comment]
@PillowPillow is this project dead or alive? :)

**Comment by PillowPillow** [comment]
Hello @mackelito , Yes this project's still alive since we're using it in production in my company' projects. 
What you are facing of is the expected behavior. The `observe()` method act as cold observable.
If you don't wanna use the decorators to bind your property you have to use the `startWith` operator to setup the start value.

````typescript
this.storage.observe('cart').pipe(
    startWith(this.storage.retrieve('card'))
).subscribe(e => console.log('e', e));
````

**Comment by mackelito** [comment]
Glad to hear it's still alive 👍 

I had totally forgotten about the concept of hot/cold observables.. 😄 thx for the reminder!
