### ISSUE TITLE
Custom Prefix Separator

### ISSUE THREAD

**Issue by ozalvarez** [PillowPillow/ng2-webstorage#14]
Hi Friends. We should let users customize the Prefix Separator. For example in angular-local-storage (angular1) the default prefix is "ls" and the separator is "." so if you create a value look like "ls.YOUR_VALUE". Here your separator is "|" and yhis value should be a variable.

In keyStorage.js i change
return CUSTOM_LIB_KEY + "|" + raw.toString().toLowerCase();
By 
return CUSTOM_LIB_KEY + "." + raw.toString().toLowerCase();

and works perfect but a new update will broke this.

**Comment by PillowPillow** [comment]
Hi, thanks for the issue. 
The keyStorage is only used by the library, you shouldn't have to care about it. I implemented some weeks ago a way to customize the prefix to avoid the naming conflicts but that's an edge case that shouldn't happen. can you explain me your use case? Why do you need to set the separator?

**Comment by ozalvarez** [comment]
Because i have a different app in the same domain using angular1 with angular-local-storage and that library use this separator ".". I'm not able to change that ap for that reasong i need to set the Local Storage and redirect to that app.

**Comment by PillowPillow** [comment]
So you need to share the values between your ng1 and ng2 apps. understood.

**Comment by ozalvarez** [comment]
EXACTLY

**Comment by PillowPillow** [comment]
The version 1.2.5 provides a new method setStorageKeySeparator. 
You can now set the separator by calling this method.
````typescript
import {KeyStorageHelper} from 'ng2-webstorage';
KeyStorageHelper.setStorageKeySeparator('.');
````

**Comment by ozalvarez** [comment]
you rock my friend
