### ISSUE TITLE
ngx-webstorage added support to angular 11, but still depends on angular 10.

### ISSUE THREAD

**Issue by mshima** [PillowPillow/ng2-webstorage#142]
**Versions (please complete the following information):**
 - NgxWebstorage: 7.0.0
 - Angular: 11.0.5

**Describe the bug**
ngx-webstorage added support to angular 11, but still depends on angular 10.

**To Reproduce**
```
npm install ngx-webstorage@7.0.0
cat node_modules/ngx-webstorage/package.json | grep @angular
```
```
    "@angular/common": "^10.0.0",
    "@angular/core": "^10.0.0"
```

**Expected behavior**
Should depend on `@angular/*@^11.0.0`

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Comment by PillowPillow** [comment]
Hello, thanks for reporting this issue. 
It should be fixed with the v7.0.1.
