### ISSUE TITLE
Add support for Angular 11

### ISSUE THREAD

**Issue by patrickrioux** [PillowPillow/ng2-webstorage#145]
Please add support for Angular 11 to avoid those warnings. I will test if the component will work on A11.
Thanks.

npm WARN ngx-webstorage@6.0.0 requires a peer of @angular/common@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-webstorage@6.0.0 requires a peer of @angular/core@^10.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by tobiasmuecksch** [comment]
This issue can be closed, since it works perfectly fine with angular 12 as of now.
