### ISSUE TITLE
SyntaxError in constants/lib.js

### ISSUE THREAD

**Issue by kashban** [PillowPillow/ng2-webstorage#15]
Hi!

I am trying to include this service into an Ionic 2 RC.0 app and when bundleing the app this error occurs:

```
[14:25:17]  bundle dev started ...
[14:25:22]  SyntaxError: Unexpected token (9:6) in C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\ng2-webstorage\dist\constants\lib.js
    at Parser.pp$4.raise (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:4072:13)
    at Parser.pp.unexpected (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2270:8)
    at Parser.pp.semicolon (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2247:59)
    at Parser.pp$1.parseVarStatement (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2614:8)
    at Parser.pp$1.parseStatement (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2398:17)
    at Parser.pp$1.parseTopLevel (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2315:23)
    at Parser.parse (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:2182:15)
    at parse (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:4972:37)
    at tryParse (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:7312:10)
    at new Module (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:7346:20)

I am working on Windows 10. Looking at that file in an editor does not seem to show any cause of this. Do you have an idea how to overcome this?
```

**Comment by PillowPillow** [comment]
Hello, i don't understand how that could happen and i can't test right now. 
Which task manager are you using gulp or webpack? With which transpiler (awesome-typescript, tsc...)? If you have the time, can you provide me a sample project that reproduce the error? i 'll check it later today.

**Comment by kashban** [comment]
Thanks for answering so quickly!

I tried this on a fresh **Ionic 2 starter** project and get the same error. So just after installing ionic with > **npm install ionic -g**, followed by `> ionic start MyDemo --ts --v2`

and add ng2-webstorage as described in the readme.md. 

`> ionic serve `

will then show that error.

This is my ionic info:

> Cordova CLI: 6.3.1
> Gulp version:  CLI version 3.9.1
> Gulp local:
> Ionic Framework Version: 2.0.0-rc.0
> Ionic CLI Version: 2.1.0
> Ionic App Lib Version: 2.1.0-beta.1
> OS:
> Node Version: v6.7.0

Package.js is:

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "ng2-webstorage": "^1.2.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.23",
    "typescript": "^2.0.3"
  },
  "description": "ionic2rc0: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```

Buildsystem with Ionic 2 RC.0 has changed from gulp to npm, so no gulptasks involved. Ionic 2 uses rollup.js for bundleing and that's where the error occurs.

I understand this is an Angular 2 library, but since Ionic 2 is based on Angular 2 it should work too.

**Comment by PillowPillow** [comment]
> I understand this is an Angular 2 library, but since Ionic 2 is based on Angular 2 it should work too.

I agree, i'm using this library in one of ionic project too but i didn't update to the rc yet. 
Thanks for the feedback, i'll check that later.

**Comment by dukeayers** [comment]
Does that mean that this project does not work with Angular 2 rc?

**Comment by PillowPillow** [comment]
No that mean that this lib seems to not work with the ionic 2 rc. 
Ng2Webstorage is currently compliant with the angular release specs but if you need a rc compliant you just have to downgrade the package version.

**Comment by kashban** [comment]
Sad indeed, since Ionic's own localstorage lib (@ionic/storage) is way over it's head with an asynchronous API for synchronous browser functionality and I had no luck including angular-2-local-storage either (service configuration does not work). 

Going to try angular2-cool-storage then until maybe Ng2Webstorage has been updated to work with Ionic 2 RC.x.

Thanks for the heads up, though, I keep this project starred.

**Comment by PillowPillow** [comment]
After a quick look the issue seems to come from the build process. I m using tsc to avoid embeding angular2 in the dist file and keep the structure and import statements but that doesn't work with rollup. 
I have currently no idea about how to fix that.. Maybe provide a npm repo with the .ts files and let rollup build the library.

**Comment by PillowPillow** [comment]
I'll try to switch from tsc to rollup tonight.

**Comment by PillowPillow** [comment]
Ok, i found a solution. A new version will be available during the night, as soon as possible. :)

**Comment by PillowPillow** [comment]
hey, the v1.3.0 is now available and should fix this issue.

**Comment by kashban** [comment]
Sounds great, thanks for the incredible quick reaction! 

Angular-Cool-Storage works for me but I will try ng2-webstorage again. 

best regards 

Jürgen

**Comment by kashban** [comment]
I confirm it's working now with Ionic 2 RC.0. Great work!!!
