### ISSUE TITLE
Systemjs Import Error

### ISSUE THREAD

**Issue by dukeayers** [PillowPillow/ng2-webstorage#16]
I have been working for a while trying to get this project to load in and play nice with my project. It may be that I am no where near being an expert in systemjs but I kept getting an error of:

 `SyntaxError: Unexpected token <`

It was a pretty generic error and it lead me to going through previous issues that have been closed until I stumbled across #1 where you explained to do the following for those using systemjs:

> The last commit fix the errors and adds a compiled version of the library. If you're using systemjs you simply have to import the ng2-webstorage in you application via import {...} from 'ng2-webstorage/index'.

I attempted to do this but I found that my solution was importing the `ng2-webstorage` as you normally would (i.e. `ng2-webstorage': 'npm:ng2-webstorage`) but the tricky part was adding the following few lines to the `packages` object:

`        packages: {
            'ng2-webstorage': {
                main: './index.js',
                defaultExtension: 'js'
            }
        }
`

Once I did this then I was able to import into app.module via `import { Ng2Webstorage } from 'ng2-webstorage';`

I definitely appreciate the support this library is gaining and I want to open the door to using this library even more to those users who are inexperienced like I am.

My question is...

 Should I have already known to do this with systemjs (again I am still learning) or should there be a section in the README that can include this tidbit in order to help users who may be experiencing the same issue as me? Or is there a different way that I should be leveraging systemjs with this **awesome** library?

Thanks again for support you have shown others!

**Comment by PillowPillow** [comment]
Hello! thanks for the feedback. I'm not a systemjs expert too, i prefer webpack by far. 
I don't know if your issue was a basic that should be know by all of us or a tricky part but if you were blocked by this, it should be in the readme.

For your information my system js sample app use the following configuration:

````typescript

(function(global) {

	// map tells the System loader where to look for things
	var map = {
		'app': 'app', // 'dist',
		'@angular': 'node_modules/@angular',
		'ng2-webstorage': 'node_modules/ng2-webstorage',
		'rxjs': 'node_modules/rxjs'
	};

	// packages tells the System loader how to load when no filename and/or no extension
	var packages = {
		'app': {main: 'main.js', defaultExtension: 'js'},
		'rxjs': {defaultExtension: 'js'},
		'ng2-webstorage': {defaultExtension: 'js'}
	};

	var ngPackageNames = [
		'common',
		'compiler',
		'core',
		'forms',
		'http',
		'platform-browser',
		'platform-browser-dynamic',
		'router',
		'upgrade',
	];
//....

````

**Comment by PillowPillow** [comment]
Hey, i added a tiny section in the readme about system js.
By the way, the last version 1.3.0 changed the build process and dist files. You now have to use bundles/core.umd.js and not index.js.

````typescript
    System.config({
        map: { 
            ...,
            ng2-webstorage': 'node_modules/ng2-webstorage'
        },
        packages: {
            ...,
            'ng2-webstorage': {main: 'bundles/core.umd.js', defaultExtension: 'js'}
        }
    });

````
