### ISSUE TITLE
Versioning npm vs. Github

### ISSUE THREAD

**Issue by Bernd-T** [PillowPillow/ng2-webstorage#169]
I'm a bit confused about the versioning.
Currently, npm says at https://www.npmjs.com/package/ngx-webstorage thet the current version is **v10.0.1** and the last publish was "2 months ago" which would be **may 2022**.

This repo here says the current version is **v8.0.0** and the last release was on **may 2021**
so is this repo still the official repo for the according npm package and if yes what is the actual version history?

**Comment by kathLes** [comment]
If you check out the tags you see that the versions from NPM are: ngx-webstorage@10.0.2, ect
Check the image for clarification: 
![image](https://user-images.githubusercontent.com/17699141/186618215-ddd3b94e-742e-4eb0-9a99-ff15d69d9c39.png)
