### ISSUE TITLE
Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by donjae** [PillowPillow/ng2-webstorage#18]
Hi, 

I'm getting an error of `TypeError: Cannot read property 'store' of undefined` 

I'm pretty sure im importing and configuring it right, but here's a sample of my code: 

app.module:  `import {Ng2Webstorage} from 'ng2-webstorage';` browser module, etc

 **and then in my service:** 
`import {LocalStorageService} from 'ng2-webstorage';
@Injectable()
export class LoginService {

    constructor (private http: Http,  private storage:LocalStorageService) {}
    private saveTokenId(res: Response) {
        let body = res.json();
        let success: boolean;
        try {
            this.storage.store('userId', 'value');
            success = true;
        } catch(e){
            console.log(e)
            success = false;
        } finally {
            return success
        }
    }`

**Comment by donjae** [comment]
Just a heads up, I'm using webpack. Not sure if that makes a difference, or if I needed to do anything with that

**Comment by PillowPillow** [comment]
Hi, i'm using webpack too and it works fine. The unit tests seems to pass too, i don't understand. 
Did you try the library with a new projects? Which typescript loader are you using? 
Can you verify that the imported file is bundles/core.umd.js (by write an console.log('foobar') on top of it)?

**Comment by donjae** [comment]
I'm pretty novice, but I hope this will answer your question. 

My typescript version is 2.0.3 (`tsc -v`)

Heres my tsconfig.json:
`{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom", "es2016.array.include"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}`

After writing writing the console.log(...) into the bundles/core.umd.js, I don't see it popping into my console. So I'm guessing it's some sort of importing issue? 

(side question: isn't that a js file? for an angular package, don't i need to add console.log(...) to a ts file in the distribution folder to test if its importing properly?)

**Comment by donjae** [comment]
>Please verify what's the value of this.storage in your saveTokenId method. 

So i've tried various ways, but right now I have it as `this.storage.store('userId', 'value');` for testing purposes (both values are strings). 

>Verify too that you didn't declare storage twice, first in the class body and after in the constructor parameters.

I double checked, and yeah, I just initialized it in the constructor and used it in my body/function. 

I did do a `console.log(this.storage)` to see if there was anything, and it actually came up as undefined.

**Comment by PillowPillow** [comment]
> After writing writing the console.log(...) into the bundles/core.umd.js, I don't see it popping into my console. So I'm guessing it's some sort of importing issue?

> (side question: isn't that a js file? for an angular package, don't i need to add console.log(...) to a ts file in the distribution folder to test if its importing properly?)

Weird.. That should be loaded. In fact webpack 1.x (and systemJS) doesn't support the es6 module syntaxe so you have to use the umd format. The package.json references this one as the main file of the library, so when you write `import {...} from 'ng2-webstorage';`, it will imports *node-modules/ng2-webstorage/bundles/core.umd.js*.
The files in the dist folder are available for the es6 bundlers like rollupjs included with ionic2 RC.0 for example.

Is your project load correctly and crash on saveTokenId call or Ng2Webstorage simply wont be imported?

Did you try to log *this.storage* in your *saveTokenId* method? I suspect it's undefined at this moment.
Can you tell me if at the constructor step the storage is correctly filled?

**Comment by PillowPillow** [comment]
> I did do a console.log(this.storage) to see if there was anything, and it actually came up as undefined.
That what i supposed. 

Please try to replace the contructor of your class by the following code and tell me what's happen.

````typescript
class Foobar {
...
constructor (private http: Http,  private storage:LocalStorageService) {
console.log(storage);    
storage.store('userId', 'value');
}
...
}
````

**Comment by donjae** [comment]
Wow, that's crazy, and I should've tried that too before I asked. Yeah, so the LocalStorageService is working, but only within the constructor. 

Not sure if it's suppose to be that way, but it's working now. Do you want to close this issue?

**Comment by PillowPillow** [comment]
> Wow, that's crazy, and I should've tried that too before I asked. Yeah, so the LocalStorageService is working, but only within the constructor.

Ok, so the issue come from your class and not the library.

> Not sure if it's suppose to be that way, but it's working now. Do you want to close this issue?

Nop, i would like to make it works for you before ^^'.
Where and how do you use the *saveTokenId* method? I bet that if you write a `console.log(this)` in it, the logged scope will not be your LoginService.

**Comment by donjae** [comment]
Ahhh, okay. that's interesting. 

So yeah, running `console.log(this)` shows MapSubscriber{object..}, which is how saveTokenID is being implemented. I guess I should've shown the whole code:

`
    private saveTokenId(res: Response) {
        let body = res.json();
        let success: boolean;
        try {
            this.storage.store('userId', 'value');
            success = true;
        } catch(e){
            console.log(e)
            success = false;
        } finally {
            return success
        }
    }

    sendToken (token: string): Observable<any> {
        let body = 'token='+token;
        let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
        let options = new RequestOptions({ headers: headers });
        return this.http.post('http://localhost:3200', body, options)
            .map(**this.saveTokenId**)
            .catch(this.handleError);
    }
`

So it makes sense now. Calling this within that scope(?), refers to the observable object.

**Comment by PillowPillow** [comment]
Yes, that was the tricky part :).
You juste have to use a lambda function and it will works like a charm.

````typescript

sendToken (token: string): Observable<any> {
    let body = 'token='+token;
    let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
    let options = new RequestOptions({ headers: headers });
    return this.http.post('http://localhost:3200', body, options)
        .map((...params) => this.saveTokenId(...params))
        .catch((...params) => this.handleError(...params));
}


````

**Comment by donjae** [comment]
Thanks for the help!

**Comment by PillowPillow** [comment]
you're welcome
