### ISSUE TITLE
Support for Angular 16

### ISSUE THREAD

**Issue by zstundys** [PillowPillow/ng2-webstorage#183]
Nuff said

**Comment by blgiorgi** [comment]
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sport@0.0.0
npm ERR! Found: @angular/common@16.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~16.0.0" from the root project        
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.0" from ngx-webstorage@11.1.1
npm ERR! node_modules/ngx-webstorage
npm ERR!   ngx-webstorage@"11.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by JamesJansson** [comment]
Just use the native `localStorage.getItem()` `localStorage.setItem()` `localStorage.removeItem()`. This package looks like it is not actively maintained which means future Angular updates will keep breaking your builds.

**Comment by PillowPillow** [comment]
Hi, I'm juste starting to upgrade our app to the v16 in my company. A new version of this package is available supporting angular16.
regards
