### ISSUE TITLE
TypeError: can't access property "get", this.strategy is undefined. Still no fix this??

### ISSUE THREAD

**Issue by logicappsource** [PillowPillow/ng2-webstorage#187]
**Versions (please complete the following information):**
    "ngx-webstorage": "11.1.1",
 - Angular: 15.1

**Describe the bug**
When retreiving any object using get or set, the following error occur: 
TypeError: can't access property "get", this.strategy is undefined.

**To Reproduce**
1. Inject the storage dependcy 
2. call any method on the service

**Expected behavior**
Receive an item for localStorage without throwing an error

**Comment by logicappsource** [comment]
issue closed the error was not related to the framework but issue by myself. Thank you

**Comment by Xstoudi** [comment]
@logicappsource Can you tell us how did you fix this error? :')
