### ISSUE TITLE
Support Angular v18

### ISSUE THREAD

**Issue by MAN-Sendance** [PillowPillow/ng2-webstorage#189]
**Is your feature request related to a problem? Please describe.**
Currently Angular v18 is not supported which leads to the following error:

```
npm ERR! Found: @angular/common@18.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from ngx-webstorage@13.0.1
```

**Describe the solution you'd like**
Please support Angular v18 as dependencies meaning upgrade the Angular-related packages to v18

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mbvb1223** [comment]
Yes, I have the same issue, please help upgrade to support Angular 18.
Thank you
