### ISSUE TITLE
__webpack_require__.i is not a function 

### ISSUE THREAD

**Issue by geronimo678** [PillowPillow/ng2-webstorage#19]
I would like to use version 1.3.0 with angular 2.0.2 and typescript 2.0.3 and angular-cli@1.0.0-beta-17, but I got the error message that 

`__webpack_require__.i is not a function`
 on line
`@SessionStorage('session_key') session_key: string;`

I went back to 1.2.4 and it works well.

**Comment by PillowPillow** [comment]
Hi, thanks for the feedback. Can you verify that's the loaded file is bundles/core.umd.js ? By writing a console.log('foobar') in it for example.

**Comment by PillowPillow** [comment]
Ok! I found a solution... A new build will be available soon.

**Comment by PillowPillow** [comment]
the v1.3.1 should solve your issue, please let me know if you encounter any other problem.

**Comment by geronimo678** [comment]
thank you very much! It's working :D very fine! I appreciate your work, it's very good!

**Comment by matheusdavidson** [comment]
Hi, I'm having a similar problem with ionic 2 on a mac, on windows if working fine:
__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_3_ng2_webstorage__["LocalStorage"]) is not a function. (In '__WEBPACK_IMPORTED_MODULE_3_ng2_webstorage__["LocalStorage"])()', '__WEBPACK_IMPORTED_MODULE_3_ng2_webstorage__["LocalStorage"])' is undefined)

**Comment by PillowPillow** [comment]
Hi, I don't have mac right now. I'll check that tomorrow.
Can you check the version that you are using ? If it's the 1.4.2 please try to downgrade to the 1.4.0, i suspect the carriage return.

**Comment by matheusdavidson** [comment]
Hi @PillowPillow, thank you for the fast response.
Tried with 1.4.0 and i have the same error.

**Comment by PillowPillow** [comment]
Ok, I reproduce the error on my mac. I'll try to fix that tonight but right now i don't understand what's going on.

**Comment by jdgeier** [comment]
I'm also having an issue with ionic2 and 1.4.2 although I'm having the issue on windows. I tried to downgrade on npm but got :
npm install --save ng2-webstorage@1.4.0
ionic-app-base@ ..
`-- ng2-webstorage@1.4.0  invalid

**Comment by PillowPillow** [comment]
hi jdgeier. There is no point to downgrade since webpack2 doesn't use the umd version but the dist one. I forgot this point when i said to matheus to try that.
On my windows, it's working fine. Can you give your ionic's version? @matheusdavidson can you do the same thing (windows and mac).

**Comment by matheusdavidson** [comment]
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.4.0
Xcode version: Not installed

**Comment by matheusdavidson** [comment]
WINDOWS: 
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.4.0
Xcode version: Not installed

**Comment by matheusdavidson** [comment]
OSX:
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v5.4.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by PillowPillow** [comment]
Hello. I'm still looking for a solution.. 
It seems that the issue appeared with the ionic's app-script v0.0.46. Digging into the patch note, i found that webpack was updated with this release so i tried to load use ng2-webstorage in an empty webpack project but it works perfectly. 
I don't understand what's going on, i'm looking further into the last commits to find something that could break the import system.

**Comment by matheusdavidson** [comment]
Now i'm getting this everywhere, windows, ubuntu and mac, it really seems to be the new app-script.

**Comment by PillowPillow** [comment]
Hi, i updated the peer deps with the last version and it seems the new version of angular compile fixed this issue. Please try and let me know if you encounter a problem with the library.

If you encounter an error `ctorParameters.map is not a function`, please update the angular version to the v2.2.x at least.
