### ISSUE TITLE
Supports Angular 19

### ISSUE THREAD

**Issue by davidshen84** [PillowPillow/ng2-webstorage#190]
**Is your feature request related to a problem? Please describe.**
Please support Angular 19.

**Describe the solution you'd like**
Please support Angular 19.

**Describe alternatives you've considered**
Stuck at Angular 18

**Comment by davidshen84** [comment]
I overrode the dependencies, and everything worked fine for my app. I think A19 did not bring any breaking changes.

**Comment by davidshen84** [comment]
https://github.com/davidshen84/davidshen84.github.io/blob/55e9a52907daba046bd960431e70dfd5d1e7ca34/package.json#L15

**Comment by BenSawary** [comment]
> Hello, I m waiting this PR : [angular-eslint/angular-eslint#2109](https://github.com/angular-eslint/angular-eslint/pull/2109) to update the whole dependencies. regards,

The PR is already merged :)

**Comment by PillowPillow** [comment]
Thanks for the reminder :D, I just deployed the new version.

**Comment by MansurIsakov** [comment]
@PillowPillow Hello, can u publish on npm as well?
