### ISSUE TITLE
LocalStorage Observable Error: 'Decorators are not valid here.'

### ISSUE THREAD

**Issue by donjae** [PillowPillow/ng2-webstorage#20]
Loving the package so far! Having just a small issue with the `LocalStorage` decorator. 

Attempting to put `@LocalStorage('value')` within the class (or outside of it) will cause an error.

I looked further into the issue, and saw #https://github.com/Microsoft/TypeScript/issues/8257, so it could possibly be just an issue with typescript compilation? 

(feel free to close out the thread if not a valid issue)

**Comment by PillowPillow** [comment]
Hello :),
Can you show me the code that threw the error?
This decorator must be on an attribute, not a class or a method.

**Comment by donjae** [comment]
Ah, so I think I see what you mean. You're talking about binding/having the decorator on a component or something (i believe?). So it's not so much for synchronizing the `'key'` value to an actual value, but like something on the DOM? 

```
import { Injectable, EventEmitter }     from '@angular/core';
import {LocalStorageService, KeyStorageHelper, LocalStorage} from 'ng2-webstorage';

@Injectable()
export class LoginService {
    @LocalStorage('key')

    constructor (private http: Http,  private storage:LocalStorageService) {
        this.storage.observe('key')
            .subscribe((newValue) => {
                this.loginStatus.emit(newValue);
            })

    }

   status = new EventEmitter<any>()

```

**Comment by PillowPillow** [comment]
A decorator is a function that decorates an element, attribute, class, method..  You can't use it without thoses elements.

Your code should be the following.

````typescript
import { Injectable, EventEmitter }     from '@angular/core';
import {LocalStorageService, KeyStorageHelper, LocalStorage} from 'ng2-webstorage';

@Injectable()
export class LoginService {
    @LocalStorage('key')`
    anAttribute; //the variable bound to *key* in the local storage

    constructor (private http: Http,  private storage:LocalStorageService) {
        this.storage.observe('key')
            .subscribe((newValue) => {
                this.loginStatus.emit(newValue);
            })

    }

   loginStatus = new EventEmitter<any>()

````

**Comment by donjae** [comment]
Ah, I feel definitely silly, cause in the examples, I thought you were declaring another/different variable.

Question though: If I change the value through dev tools on the browser, it should detect/observe the change? Or is it only through `this.storage.store`, that it will detect a change?

**Comment by donjae** [comment]
Lol, it's working now.

I figured out my issue. I was changing values through the browser dev tools, to see if it observed the changes (it didn't). But once I implemented some tests using your methods, I saw that it did observe the changes. Good to know that it can only detect changes through your methods, and was confused as to if I did something wrong on my end. 

Thanks again!

**Comment by PillowPillow** [comment]
> Question though: If I change the value through dev tools on the browser, it should detect/observe the change? Or is it only through this.storage.store, that it will detect a change?

Nop it shouldn't detect changes, you need to call `this.storage.store(...)` or assign a bound variable `this.anAttribute = 'hello'`.

Btw, the library includes a cache system, so if you change a value in the storage during a test session, this value will not change in the app. You need to refresh the page after any direct change in the localStorage/sessionStorage to ensure that the lib takes the new value.
