### ISSUE TITLE
Ng2Webstorage possibly causes error on angular i18n module

### ISSUE THREAD

**Issue by t4ss5t** [PillowPillow/ng2-webstorage#21]
I just configured the built-in Angular i18n service to my project that uses Ng2Webstorage.

On calling "ng-xi18n", the following error occurs:
```
Error: Unexpected value 'Ng2Webstorage' imported by the module 'AppModule'
    at C:\Users\XYZ\node_modules\@angular\compiler\bundles\compiler.umd.js:14126:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\XYZ\node_modules\@angular\compiler\bundles\compiler.umd.js:1411
1:46)
    at C:\Users\XYZ\node_modules\@angular\compiler\bundles\compiler.umd.js:12952:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (C:\XYZ\node_modules\@angular\compiler\bundles\compiler.umd.js:12951:21)
    at Extractor.extract (C:\XYZ\node_modules\@angular\compiler-cli\src\extract_i18n.js:92:47)
    at extract (C:\XYZ\node_modules\@angular\compiler-cli\src\extract_i18n.js:16:35)
    at Object.main (C:\XYZ\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\XYZ\node_modules\@angular\compiler-cli\src\extract_i18n.js:160:9)
Extraction failed
```

Maybe it just a configuration mistake that I have done, but perhaps it is possible to add  *.metadata.json files to fix the problem.

Can anyone evaluate this?

**Comment by PillowPillow** [comment]
Hi, i never encountered this error. Can you show me how you're importing the library? 
I assume you're using angular-cli so webpack 2, am i right?

**Comment by t4ss5t** [comment]
Hi,

yes i'm using angular-cli (beta-16), I think webpack is included.

I configured the xi18n tool according to this howto-guide: https://angular.io/docs/ts/latest/cookbook/i18n.html#!#create-a-translation-source-file-with-the-_ng-xi18n_-tool
I added the i18n directive to some HTML tags (like described in "Mark text with the i18n attribute") and finally started the ng-xi18n tool. As result the error occurs.

It seems that "angular2-moment" had a similar error: https://github.com/urish/angular2-moment/issues/68 . That's where I found the approach with the *.metadata.json files.

**Comment by PillowPillow** [comment]
Hi, i pushed a new version on npm 1.3.1-beta
Can you try it with your project?

**Comment by PillowPillow** [comment]
Hi, the v1.3.3 should fix your issue. Please let me know if you encounter any other issue.

**Comment by PillowPillow** [comment]
no news? I assume the problem was solved with the last build. I close this issue, feel free to open another if you want.

**Comment by t4ss5t** [comment]
Sorry for my late response. I tested the new version successfully, the error has gone - Thank you!
