### ISSUE TITLE
Warning message while starting node server

### ISSUE THREAD

**Issue by kishorek129** [PillowPillow/ng2-webstorage#22]
I'm getting this warning massage in my server console. can you please help me to resolve it?

Cannot find SourceMap 'data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29yZS51bWQuanMiLCJzb3VyY2VzIjpbIi4uL2Rpc3QvZW51bXMvc3RvcmFnZS5qcyIsIi4uL2Rpc3QvY29uc3RhbnRzL2xpYi5qcyIsIi4uL2Rpc3QvaGVscGVycy9rZXlTdG9yYWdlLmpzIiwiLi4vZGlzdC9oZWxwZXJzL3N0b3JhZ2VPYnNlcnZlci5qcyIsIi4uL2Rpc3QvaGVscGVycy9tb2NrU3RvcmFnZS5qcyIsIi4uL2Rpc3QvaGVscGVycy93ZWJTdG9yYWdlLmpzIiwiLi4vZGlzdC9zZXJ2aWNlcy93ZWJTdG9yYWdlLmpzIiwiLi4vZGlzdC9zZXJ2aWNlcy9sb2NhbFN0b3JhZ2UuanMiLCIuLi9kaXN0L3NlcnZpY2VzL3Nlc3Npb25TdG9yYWdlLmpzIiwiLi4vZGlzdC9kZWNvcmF0b3JzL3dlYlN0b3JhZ2UuanMiLCIuLi9kaXN0L2RlY29yYXRvcnMvbG9jYWxTdG9yYWdlLmpzIiwiLi4vZGlzdC9kZWNvcmF0b3JzL3Nlc3Npb25TdG9yYWdlLmpzIiwiLi4vZGlzdC9hcHAuanMiXSwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IHZhciBTVE9SQUdFO1xyXG4oZnVuY3Rpb24gKFNUT1JBR0UpIHtcclxuICAgIFNUT1JBR0VbU1RPUkFHRVtcImxvY2FsXCJdID0gMF0gPSBcImxvY2FsXCI7XHJcbiAgICBTVE9SQUdFW1NUT1JBR0VbXCJzZXNzaW9uXCJdID0gMV0gPSBcInNlc3Npb25cIjtcclxufSkoU1RPUkFHRSB8fCAoU1RPUkFHRSA9IHt9KSk7XHJcbi8vIyBzb3VyY2VNYXBwaW5nVVJMPXN0b3JhZ2UuanMubWFwIiwiaW1wb3J0IHsgU1RPUkFHRSB9IGZyb20gJy4uL2VudW1zL3N0b3JhZ2UnO1xyXG5leHBvcnQgdmFyIExJQl9LRVkgPSAnbmcyLXdlYnN0b3JhZ2UnO1xyXG5leHBvcnQgdmFyIExJQl9LRVlfU0VQQVJBVE9SID0gJ3wnO1xyXG5leHBvcnQgdmFyIFNUT1JBR0VfTkFNRVMgPSAoX2EgPSB7fSxcclxuICAgIF9hW1NUT1JBR0UubG9jYWxdID0gJ2xvY2FsJyxcclxuICAgIF9hW1NUT1JBR0Uuc2Vzc2lvbl0gPSAnc2Vzc2lvbicsXHJcbiAgICBfYVxyXG4pO1xyXG52YXIgX2E7XHJcbi8vIyBzb3VyY2VNYXBwaW5nVVJMPWxpYi5qcy5tYXAiLCJpbXBvcnQgeyBMSUJfS0VZLCBMSUJfS0VZX1NFUEFSQVRPUiB9IGZyb20gJy4uL2NvbnN0YW50cy9saWInO1xyXG52YXIgQ1VTVE9NX0xJQl9LRVkgPSBMSUJfS0VZO1xyXG52YXIgQ1VTVE9NX0xJQl9LRVlfU0VQQVJBVE9SID0gTElCX0tFWV9TRVBBUkFUT1I7XHJcbmV4cG9ydCB2YXIgS2V5U3RvcmFnZUhlbHBlciA9IChmdW5jdGlvbiAoKSB7XHJcbiAgICBmdW5jdGlvbiBLZXlTdG9yYWdlSGVscGVyKCkge1xyXG4gICAgfVxyXG4gICAgS2V5U3RvcmFnZUhlbHBlci5yZXRyaWV2ZUtleXNGcm9tU3RvcmFnZSA9IGZ1bmN0aW9uIChzdG9yYWdlKSB7XHJcbiAgICAgICAgcmV0dXJuIE9iamVjdC5rZXlzKHN0b3JhZ2UpLmZpbHRlcihmdW5jdGlvbiAoa2V5KSB7IHJldHVybiBrZXkuaW5kZXhPZihDVVNUT01fTElCX0tFWSkgPT09IDA7IH0pO1xyXG4gICAgfTtcclxuICAgIEtleVN0b3JhZ2VIZWxwZXIuZ2VuS2V5ID0gZnVuY3Rpb24gKHJhdykge1xyXG4gICAgICAgIGlmICh0eXBlb2YgcmF3ICE9PSAnc3RyaW5nJylcclxuICAgICAgICAgICAgdGhyb3cgRXJyb3IoJ2F0dGVtcHQgdG8gZ2VuZXJhdGUgYSBzdG9yYWdlIGtleSB3aXRoIGEgbm9uIHN0cmluZyB2YWx1ZScpO1xyXG4gICAgICAgIHJldHVybiBcIlwiICsgQ1VTVE9NX0xJQl9LRVkgKyBDVVNUT01fTElCX0tFWV9TRVBBUkFUT1IgKyByYXcudG9TdHJpbmcoKS50b0xvd2VyQ2FzZSgpO1xyXG4gICAgfTtcclxuICAgIEtleVN0b3JhZ2VIZWxwZXIuc2V0U3RvcmFnZUtleVByZWZpeCA9IGZ1bmN0aW9uIChrZXkpIHtcclxuICAgICAgICBpZiAoa2V5ID09PSB2b2lkIDApIHsga2V5ID0gTElCX0tFWTsgfVxyXG4gICAgICAgIENVU1RPTV9MSUJfS0VZID0ga2V5O1xyXG4gICAgfTtcclxuICAgIEtleVN0b3JhZ2..........
FDLEFBQ0wsOzs7Ozs7Ozs7LDs7LDs7In0=': Error: Cannot resolve 'file' or'directory'./data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY.............
DQUFDO2dCQUNuQixnQkFBZ0IsQ0FBQyxLQUFLLENBQUMsS0FBSyxFQUFFLElBQUksRUFBRSxLQUFLLENBQUMsQ0FBQzthQUM5QztTQUNKLENBQUMsQ0FBQztLQUNOLENBQUM7Q0FDTCxDQUFDLEFBQ0Y7O0FDYk8sSUFBSSxZQUFZLEdBQUcsU0FBUyxxQkFBcUIsQ0FBQyxhQUFhLEVBQUU7SUFDcEUsT0FBTyxVQUFVLENBQUMsYUFBYSxFQUFFLE9BQU8sQ0FBQyxLQUFLLENBQUMsQ0FBQztDQUNuRCxDQUFDLEFBQ0Y7O0FDSE8sSUFBSSxjQUFjLEdBQUcsU0FBUyx1QkFBdUIsQ0FBQyxhQUFhLEVBQUU7SUFDeEUsT0FBTyxVQUFVLENBQUMsYUFBYSxFQUFFLE9BQU8sQ0FBQyxPQUFPLENBQUMsQ0FBQztDQUNyRCxDQUFDLEFBQ0Y7O0FDQ08sSUFBSSxhQUFhLEdBQUcsQ0FBQyxZQUFZO0lBQ3BDLFNBQVMsYUFBYSxHQUFHO0tBQ3hCO0lBQ0QsYUFBYSxDQUFDLFVBQVUsR0FBRztRQUN2QixFQUFFLElBQUksRUFBRUUsc0JBQVEsRUFBRSxJQUFJLEVBQUUsQ0FBQztvQkFDYixZQUFZLEVBQUUsRUFBRTtvQkFDaEIsU0FBUyxFQUFFLENBQUMscUJBQXFCLEVBQUUsbUJBQW1CLENBQUM7b0JBQ3ZELE9BQU8sRUFBRSxFQUFFO2lCQUNkLEVBQUUsRUFBRTtLQUNoQixDQUFDOztJQUVGLGFBQWEsQ0FBQyxjQUFjLEdBQUcsRUFBRSxDQUFDO0lBQ2xDLE9BQU8sYUFBYSxDQUFDO0NBQ3hCLEVBQUUsQ0FBQyxDQUFDLEFBQ0wsOzs7Ozs7Ozs7LDs7LDs7In0= in \node_modules\ng2-webstorage\bundles

**Comment by kishorek129** [comment]
Hi 
Please find from blow details.
Node 4.4.2
Task manager  - webpack
angular version - 2.1.0.

**Comment by PillowPillow** [comment]
Ok. you didn't answered to one of my questions. Are you using angular universal? Because node shouldn't throw this sort of error except if you require the module inside a node instance. Please share me your webpack config (just the loader part, it should be enough).

Did you try to start the example inside this repo?

**Comment by kishorek129** [comment]
No i haven't use the angular universal. 

loaders: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        exclude: [/\.(spec|e2e)\.ts$/]
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.css$/,
        loader: 'raw-loader'
      },
	 { 
		test: /\.less$/,  
		exclude: /node_modules/, 
		loader: 'raw-loader!less-loader' 
	  },
	  { 
		test: /\.async\.ts$/, loaders: ['es6-promise-loader', 'ts-loader'], exclude: [ /\.(spec|e2e)\.ts$/ ] 
	  },
      {
        test: /\.html$/,
        loader: 'raw-loader',
        exclude: [helpers.root('client/index.html')]
      }
    ]

**Comment by PillowPillow** [comment]
Hi, sorry for the response delay. I didn't achieve to reproduce your error with the same config than yours.. 
Try to run the example project in this repo by running *npm run dev* and tell me if it works. Make sure to import the bundled version of the library by replacing the content of *example/libwrapper.ts* by the following code.
```typescript
//export * from '../bundles/core.umd.min.js';
export * from '../bundles/core.umd.js';
//export * from '../lib/app';
```

A solution to avoid the warning that you encounter may be to import the minified version of the library core.umd.min.js and not core.umd.js. I don't want to remove the sourcemap from the umd file because it's really usefull for debugging.

**Comment by PillowPillow** [comment]
Hi! Better late than never.
I encountered your issue and found the origin. The [source-map-loader](https://github.com/webpack/source-map-loader) that you're using doesn't handle the charset in inline source-maps. I'll create a pull request on his github.

Have a nice day.

**Comment by PillowPillow** [comment]
https://github.com/webpack/source-map-loader/pull/21
