### ISSUE TITLE
localStorage.observe not worked for changes in other window

### ISSUE THREAD

**Issue by MurgaNikolay** [PillowPillow/ng2-webstorage#23]
In window 1 I use

     this.storage.observe('boundValue')
        .subscribe((newValue) => {
          console.log(newValue);
        })

In window 2 I set new value `this.storage.store('boundValue', 'new value')` and I have nothing.
Will be good to observe changes from other windows.

**Comment by PillowPillow** [comment]
Hi, this behavior is normal.
The lib don't uses directly the stored value but uses a cached version instead to avoid serialize/deserialize. To do what you wan't, i must implement a control that will be triggered every Xs verifying if the stored value didn't changed. 
I'm not a huge fan but I'll think about it and come back to you soon.

**Comment by MurgaNikolay** [comment]
Now I use `storage` event for `window` to handle external localStorage changes.
This solution is bypassing your module. This issue arose for this reason.

**Comment by PillowPillow** [comment]
Thanks for this answer, I didn't know this event. I will implement it this week.

**Comment by PillowPillow** [comment]
The last version fix your issue.
Make sure to check the changelog, there is a breaking change with the service configuration.
Please tell me if you encounter any issue.

**Comment by MarcGiffing** [comment]
I'm still have a problem here. I'm using JHipster with JWT tokens which are stored in the local storage. When I log out one one tab I'm still logged in in the other tab cause of the caching mechanism. I need to refresh the page to be logged out. Is there a posibillity to disable the cache for specific keys to prevent this behavior so I can open an issue in the JHipster project or does the mentioned refreshing on multiple tabs not implemented?

**Comment by PillowPillow** [comment]
The cache shouldn't be a problem, if a change occurs in tabs, it should be reflected into the others. If you think that there is an issue with this behavior, please open an issue with a sample repo and a procedure to reproduce the problem.

Have a nice day
Nicolas
