### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by Z2710** [PillowPillow/ng2-webstorage#25]
Hello,

When using the decorators, It appears that the synchronization to the session storage and local storage does not happen properly. See below :

```
import { LocalStorage, SessionStorage} from 'ng2-webstorage';
@Component({
    selector: 'game', 
    templateUrl: 'game.component.html',
    styleUrls: ['game.component.css']
})
export class GameComponent 
{ 
    @LocalStorage("default") private test: number;
     constructor(  ) {
        this.test = 1234;    // Local storage is set to 1234
        //  ....
        // other code
        //  ...

        this.test = 5678;  // Local storage remains at 1234
  }
}
```

**Comment by PillowPillow** [comment]
Hi, I tried to reproduce your issue in this sandbox project with the following code.

````typescript
import {Component, OnInit} from '@angular/core';
import {FormGroup, FormBuilder, Validators} from '@angular/forms';
import {SessionStorageService, SessionStorage, LocalStorage} from '../../../libwrapper';

@Component({
	selector: 'app-form',
	template: `
		<form [formGroup]="form" novalidate (submit)="submit(form.value, form.valid);">
			<textarea formControlName="text"></textarea>
			<button type="submit">submit</button>
			<button type="button" (click)="clear()">clear</button>
		</form>
		<input type="text" [(ngModel)]="sessionBind">
		<input type="text" [(ngModel)]="localBind">
	`,
})
export class AppForm implements OnInit {

	form: FormGroup;

	@SessionStorage('variable')
	public sessionBind;
	@LocalStorage('variable')
	public localBind;

	constructor(private fb: FormBuilder, private sessionS: SessionStorageService) {
		this.sessionBind = 'test 1';
		console.log(this.sessionBind);  // Local storage is set to test 1
		this.sessionBind = 'test 2';
		console.log(this.sessionBind);  // Local storage is set to test 2
	}

	ngOnInit() {
		this.form = this.fb.group({
			text: this.fb.control(this.sessionS.retrieve('variable'), Validators.required)
		});
		this.sessionS.observe('variable')
		.subscribe((data) => console.log('data: ', data));
	}

	submit(value, valid) {
		this.sessionS.store('variable', value.text);
	}

	clear() {
		this.sessionS.clear();
	}

}
````

There is no problem with the synchronization. Moreover the unit tests seems to work perfectly.
Is this code like yours? Which browser are you using? Can you try to run the included example in this lib?

**Comment by Z2710** [comment]
Hello Nicolas,

I suspect the problem happens when the variable you are trying to
synchronize is an array. I tried with a "string" instead of a "sting[]",
and the synchronization was happening properly.
Here is my code. The "test2" is not sent to the local storage.

*import { Component } from '@angular/core';*
*import { LocalStorage, SessionStorage} from 'ng2-webstorage';*


*@Component({*
*    selector: 'game', *
*    templateUrl: 'game.component.html',*
*    styleUrls: ['game.component.css']*
*})*
*export class GameComponent *
*{ *
*    private wordIdList: string[];*
*    @LocalStorage("default") private myVariable: string[];*


*    constructor( ) {*

*        this.myVariable = ["test"];*
*        setTimeout ( () =>{ *
*            this.myVariable.push("test2");*
*            console.info <http://console.info>(this.myVariable);*
*        } *
*        , 5000);*
    }

}

thanks,

Fabrice

**Comment by PillowPillow** [comment]
Ok! Like i said in an old issue (#12), this library is based upon the javascript's accessors. To trigger the change event you have to assign something to the variable. 
By calling the push method you don't change the reference so i can't handle anything.

---


> Hello, the library is based on accessors so the update triggers only on value change. When you update the inner value of an object or an array, the reference doesn't change and the accessors aren't triggered. There is no trick to solve that issue without dirty check every Xms the content of your array which is a solution that i'll never implement.
> 
> To fix your problem you have to trigger the get accessor by assigning the bound property to itself (that should be enough) or changing your array reference.
> 
````typescript
import {LocalStorage} from 'ng2-webstorage';

class FooBar {

    @LocalStorage('prop')
    myArray;

    updateValue() {
        this.myArray.push('foobar');
        this.myArray = this.myArray; // should be enough 
        // this.myArray = [...this.myArray]; change the array reference
        // this.myArray = this.myArray.slice(0); same thing
    }

}
````

**Comment by GeertJohan** [comment]
I think this should be in the README/docs. I tried using the decorator on a field which has a class (object0 type, and found that changes to the fields inside that object didn't converge into the WebStorage. Using the `this.foo = this.foo;` assignment to trigger the modified accessors works works nicely, but I had to find this issue to get it work.

**Comment by PillowPillow** [comment]
https://github.com/PillowPillow/ng2-webstorage#knownissues
