### ISSUE TITLE
KeyStorageHelper missing in v1.4.x - breaking change

### ISSUE THREAD

**Issue by deepu105** [PillowPillow/ng2-webstorage#26]
v1.4.x seems to be missing KeyStorageHelper which was available in 1.3.0. Its a breaking change and doesnt compy to semver guideline. I couldnt find any mention or deprecation warning as well. So how can we set a global prefix now?

Note we are using this in https://github.com/jhipster/generator-jhipster

**Comment by deepu105** [comment]
Ok I found this in readme 
`//Ng2Webstorage.forRoot({ prefix: 'custom', separator: '.' }) The forRoot method allows to configure the prefix and the separator used by the library` 
but it would be nice to let people know that there is a breaking change and even better would have been to release a major version

**Comment by PillowPillow** [comment]
Hi, there is a changelog file describing what you want. [changelog.md](https://github.com/PillowPillow/ng2-webstorage/blob/master/CHANGELOG.md)

**Comment by deepu105** [comment]
Ok thanks.

Thanks & regards,
Deepu
