### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by clozanosanchez** [PillowPillow/ng2-webstorage#27]
I am using angular@2.4.1. My purpose is to do AOT compilation with ngc, but I receive this error from ngc:

> Error: Error encountered resolving symbol values statically. Calling function 'Ng2Webstorage', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/carlos/Documents/Workspaces/Angular Workspace/myapp/src/app/app.module.ts.

The code of AppModule is:
```
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';

import {Ng2Webstorage} from 'ng2-webstorage';

...

@NgModule({
    imports: [BrowserModule, Ng2Webstorage.forRoot({prefix: 'MYAPP', separator: '_'}), ...],
    declarations: [...],
    bootstrap: [...]
})
export class AppModule { }
```

I think your library is prepared for AOT and I am initialising correctly in my AppModule. Do you have any clue about what can be failing?

**Comment by PillowPillow** [comment]
Hi, the v1.4.3 should fix your issue. Please use the exposed fn `configure` instead of `forRoot` to define the prefix and the separator.

Example :
````typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {Ng2Webstorage, configure} from 'ng2-webstorage';

configure({ prefix: 'custom', separator: '.' });

// import {Ng2Webstorage, configure: WebstorageConfigure} from 'ng2-webstorage'; // Don't forget you can make an alias if the configure key is already in use
// WebstorageConfigure({ prefix: 'custom', separator: '.' });

@NgModule({
    declarations: [...],
    imports: [
        BrowserModule,
        Ng2Webstorage,
    ],
    bootstrap: [...]
})
export class AppModule {
}
````

**Comment by clozanosanchez** [comment]
Thank you very much. I did the alias using 'as' instead of colon because it was failing:
`import {Ng2Webstorage, configure as WebstorageConfigure} from 'ng2-webstorage';`

**Comment by PillowPillow** [comment]
edited, thank you.
