### ISSUE TITLE
Is there anyway to change the LIB_KEY through some config? 

### ISSUE THREAD

**Issue by yonimoses** [PillowPillow/ng2-webstorage#3]

**Comment by PillowPillow** [comment]
Hi, not at this moment, but it's really easy to implement. I can't do it right now but i'll try to add it soon.

**Comment by PillowPillow** [comment]
Hi, the last version provides your requested feature. You juste have to use the *setStorageKeyPrefix* method of the KeyStorageHelper before your app code.

```typescript
import {KeyStorageHelper} from 'ng2-webstorage';
KeyStorageHelper.setStorageKeyPrefix('foobar');
````
