### ISSUE TITLE
Ionic 2 importing not working

### ISSUE THREAD

**Issue by renannobile** [PillowPillow/ng2-webstorage#30]
Hello, I'm currently developing an Ionic 2 app.
I installed the package through npm and added to my app.module.ts, but when I try to use it in my service I get an error:
![error](https://cloud.githubusercontent.com/assets/15070719/21718796/f05d151c-d400-11e6-8c2f-19cb86f48b9a.png)

**Comment by PillowPillow** [comment]
Hello, thx for the feedback.

That error.. again.. the same over and over each time they update something in their framework. I'll check that and cry again.
In fact, the import system seems to load some parts of my library in async with ionic for whatever reason, resulting the services and decorators are undefined at the startup..

**Comment by PillowPillow** [comment]
...


````typescript
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';
import * as WebStorage from 'ng2-webstorage';
console.log(WebStorage); // Don't forget the console.log! ...
var {Ng2Webstorage} = WebStorage;

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    Ng2Webstorage,
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}

````



If you import the library in you module with that way (don't forget the console.log), it should works... I love that kind of bug.

**Comment by renannobile** [comment]
Thanks for the answer buddy, I'll try that approach.

**Comment by PillowPillow** [comment]
k, i'll try to fix that asap
