### ISSUE TITLE
Store JSON objects with serializer/deserializer

### ISSUE THREAD

**Issue by britztopher** [PillowPillow/ng2-webstorage#31]
Maybe I missed it in documentation, but it appears theres no way to store and retrieve JSON objects, just literals.  If its not already implemented all you would need to do is add a wrapper for `JSON.stringify(json)` for serializing and `JSON.parse(json)` for deserializing.  As for now, I am just able to store singe values

**Comment by PillowPillow** [comment]
Hi, did you try to store a json before submitting this issue?.. Like the documentation said, the library can handle any serializable value, including the json.. If not it's a bug or a bad usage.
