### ISSUE TITLE
Serialization Doesn't Work For Objects

### ISSUE THREAD

**Issue by davidwilcox** [PillowPillow/ng2-webstorage#33]
I've seen you say in a lot of other issues that this library should work for objects. In my experience it doesn't. Here's some code that demonstrates the point:

test.component.ts:
```
import { Component, OnInit } from '@angular/core';

import { SessionStorage } from 'ng2-webstorage';

class MyClass {
  var: string;
}

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css']
})
export class TestComponent implements OnInit {

  @SessionStorage()
  myObj: MyClass;
  @SessionStorage()
  direct: string;

  constructor() { }

  ngOnInit() {
    if (!this.myObj)
      this.myObj = new MyClass();
  }

}
```

test.component.html
```
<input [(ngModel)]="myObj.var">
<br>
<input [(ngModel)]="direct">
```

After testing the page, you can see my screenshot along with looking at the session local variables in Chrome. Notice that the object is not serialized properly. We do not get its member. The direct string does work.
![screenshot from 2017-01-25 20-41-16](https://cloud.githubusercontent.com/assets/253677/22319309/bba090ea-e33e-11e6-996e-ee6bd5048b20.png)

**Comment by PillowPillow** [comment]
Hi david, your test can't work since you update directly a property of your object and not its reference. Ng2Webstorage handle all serializable data but can't be aware of what you're doing in an object (I don't wan't to implement a dirty check, verifying every Xms all the nested properties of your bound objects..). If you want that the lib save your data you just have to trigger the accessor.

cf #12

**Comment by davidwilcox** [comment]
OK. It would be very helpful if this were on the documentation somewhere (that for it to work with objects, you need to do some workarounds/hacks on the client-side). I didn't see that on your documentation page. Is it there?

**Comment by PillowPillow** [comment]
You are totally right, i think the same thing but i don't really have the time to update the library right now. Feel free to make a pr if you can. In any case, I'll add it soon to avoid next missunderstandings.
