### ISSUE TITLE
issue with angular universal. Exception: Call to Node module failed with error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by consigliory** [PillowPillow/ng2-webstorage#35]

**Comment by PillowPillow** [comment]
Hello, i'm not experienced with angular universal but i think i just have to test de window object before calling it to remove this error. However I'm not sure the library will be compliant with angular universal after this fix. Can you provide me a sandbox (a repo with the dev environment) to test the library?

**Comment by PillowPillow** [comment]
No response after 20+ days, I'm closing this issue. If someone need this feature, feel free to open another one with a sandbox repository that i could use to implement it.
