### ISSUE TITLE
JSON.parse(value) when retrieve ?

### ISSUE THREAD

**Issue by youneschaoui** [PillowPillow/ng2-webstorage#37]
is it possible to define custom transformation each time we retrieve a value ? I store a hole JSON object as a value and I need to parse it each time I retrieve or bind to attribute using a decorator ?

**Comment by PillowPillow** [comment]
The library doesn't provide a transform method out of the box but it easy to do with accessors.
You can do something like that : 

````typescript

@Component({
    selector: 'foo',
    template: `
        <section>{{boundAttribute}}</section>
    `,
})
export class FooComponent {

    @LocalStorage('boundValue')
    boundAttribute;
    
    get attributeProperty() {
        return this.boundAttribute.deep.property;
    }

}

````
