### ISSUE TITLE
local storage - deleting a key only impacts the current tab in the browser

### ISSUE THREAD

**Issue by MarcGiffing** [PillowPillow/ng2-webstorage#38]
Hi,

see #23

The deletion of a key only impacts the current tab and all other tabs will retrieve the key from the javascript cache object which is not updated. (maybe it works as designed :-))

The problem I'm facing is when storing sensitive data which should be deleted (is logged in?) but still remains until the page is refreshed.

I've created my first little example with plnkr - hopefully with no errors:

http://plnkr.co/edit/S9nWN60fpS6TLUEbWf5L?p=preview&open=app%2Fapp.component.ts

- Open the link and click on "Set Key in local storage"
- Open a second tab. You'll se that the key is already setted
- Click "Delete key from local storage" in one tab
- Go to the other tab and click set key in local storage - you'll get the alert that the key is retrieved from the storage 

Thanks in advance!
Marc

**Comment by PillowPillow** [comment]
Thanks for the issue, I'll look this tomorrow and come back to you as soon as possible.

**Comment by PillowPillow** [comment]
The last version should solve your issue. Please let me know if it's ok for you.

**Comment by MarcGiffing** [comment]
Thank you very much!

**Comment by alaaelsm** [comment]
hello, I am still having this issue.
using LocalStorageService, when clear a key clear("myKey"), then close the browser tab, open another tab, lookup the key, I still get it for some reason.

I found a temp workaround by clearing the whole storage, using localStorageService.clear();

using version 1.8. 
appreciate your feedback.

**Comment by alaaelsm** [comment]
one more thing that might help, apparently this issue only occurs to keys with __json__ values, when I store plain values (simple strings/numbers) , this issue doesn't replicate.
