### ISSUE TITLE
error TS2305: Module '".../node_modules/ng2-webstorage/index"' has no exported member 'localStorage'

### ISSUE THREAD

**Issue by uzumakinaruto123** [PillowPillow/ng2-webstorage#4]
I am getting above error while importing `localStorage `. `LocalStorageService` is imported correctly.
Help is appreciated. Thanks.

**Comment by uzumakinaruto123** [comment]
That was because , i copied it from the doc. It was suppose to be `LocalStorage` . Please correct the doc. In `clear` example.

**Comment by PillowPillow** [comment]
fixed, thanks for the issue
