### ISSUE TITLE
Angular 4.0.0

### ISSUE THREAD

**Issue by kucharzyk** [PillowPillow/ng2-webstorage#40]
Will ng2-webstorage be updated to use new Angular 4.0.0?

Or maybe will be new ng4-webstorage  library?

Final version was released today

**Comment by PillowPillow** [comment]
Sure, the library will be updated to be compliant with the new version of angular. I'll try to do that for the start of the next week. About the naming i don't really know what to do. I would like to use ngx-webstorage as new package name but it seems that somebody already use it on npm..

**Comment by jbeck8176** [comment]
We do plan on maintaining that package. The package is maintained by our whole dev staff at Renovo Solutions. Feel free to use and/or contribute.

https://github.com/RenovoSolutions/ngx-webstorage

**Comment by PillowPillow** [comment]
Hi sorry i was a bit busy the last few days.
The v1.6.0 built by the ng4 compiler will be available today.

Thanks @jbeck8176 , here is my npm user name *polochon*

**Comment by jbeck8176** [comment]
@PillowPillow it's all your's

**Comment by PillowPillow** [comment]
Awesome, thank you.
