### ISSUE TITLE
Better default values for @LocalStorage() Decorator

### ISSUE THREAD

**Issue by dopry** [PillowPillow/ng2-webstorage#43]
It would be nice to be able to set the default value for properties marked up with @LocalStorage(). 

Here is an example of an ideal usage from an AuthService. 

```
@LocalStorage('AuthService.user')		  
protected user = ANONYMOUS;
```

Currently, if you set user, then reload the page local storage is overwritten with anonymous on object initialization. 

I wish that if 'AuthService.user' was set user would be assign to it instead of ANONYMOUS on object construction.  Alternatively, it would be nice to specify the default in the Decorator if it's not possible to maintain the TS default property value semantics like  ```@LocalStorage('AuthService.user', ANONYMOUS)```

Currently we work around this in our constructor as follows, 

```
 let storedUser = this.storage.retrieve('AuthService.user');
    if (storedUser) {
      this.user = storedUser;
    } else {
      this.user = ANONYMOUS;
    }
```

which is a lot of boilerplate to carry around for a default value.

**Comment by PillowPillow** [comment]
Hi, i agree with you the current behavior needs a bit of boilerplate to  use a default value. Unfortunately i can't determine at the decorator level if i am at the initialization step and i shouldn't override an existing value or not. 

The best i could do would be add another parameter to the decorator which would be the default value.

**Comment by dopry** [comment]
I think a second argument to the decorator does the job, I'd love to see that come through.

**Comment by PillowPillow** [comment]
Hello, the last version add the support for default value.
````typescript
@LocalStorage('key', 'default value')		  
foobar;
````
