### ISSUE TITLE
decorated properties unable to get localstorage value promptly during app initialization for Angular 4.0

### ISSUE THREAD

**Issue by owen26** [PillowPillow/ng2-webstorage#46]
It was fine before I upgrade my project to ng4.0.1

I have a APP_INITIALIZER provider in my app module. I do some data initialization in it. Previously all my services in this initialization process that have properties decorated with `@LocalStorage()` works perfectly fine and they are able to get initial values as long as my browser localstorage have the data needed.

But since I upgraded to angular 4.0, it can no longer get initial values in APP_INITIALIZER provider. They are undefined.

I upgraded ng2-webstorage to the newest version 1.6.2

(`@LocalStorage()` works fine when app initialization is finished)

**Comment by PillowPillow** [comment]
Hello, i m sorry that you encountered an error with the new version. Can you try the v1.5.1 and tell me if it works? the v1.6.x is globally the same thing built with the ng4 compiler adn some bug fixes.
Moreover, can you provide me a repository with a sample of your issue, i m unable to reproduce it only with your informations.

**Comment by owen26** [comment]
Hi Nicolas,

I've created a demo repository to reproduce this issue.

Actually I kinda figured out why it happens.

In ng4, if I don't customise prefix and separator by using `forRoot()`, everything is still fine.

It turns out it trying to get the initial value by default prefix rather than my customized prefix, so it can not find the value.

**Comment by PillowPillow** [comment]
Thanks, i'll look the repo and i come back to you as soon as possible.

**Comment by PillowPillow** [comment]
Hi, i looked over your demo and i had an question. Why don't you reference Ng2Webstorage as a dependency of your APP_INITIALIZER provider? It should solive your issue.

Ex from your demo :
````typescript


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    Ng2Webstorage.forRoot({ prefix: 'xn', separator: '.' })
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (demo: DemoService) => () => demo.initMyApp(),
      deps: [DemoService, Ng2Webstorage],
      multi: true,
    },
    DemoService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

````

**Comment by owen26** [comment]
Thanks, it worked!  👍 

The reason I didn't put `Ng2Webstorage` as dependency for APP_INITIALIZER is that I thought only services directly injected for `useFactory` method need to be referenced. 

And interestingly they worked fine before ng4.0.
