### ISSUE TITLE
AoT Support

### ISSUE THREAD

**Issue by bashoogzaad** [PillowPillow/ng2-webstorage#47]
Firstly, this is a great library (one of the best for localstorage in my opinion). 

It seems the library does not support aot, but this is hard to debug (Runtime compiler is not loaded). Does it support AoT? If not, are you planning to support it?

**Comment by PillowPillow** [comment]
Hi, the library already supports AOT. Which version of angular, angularci and ng2-webstorage are you using?

**Comment by bashoogzaad** [comment]
I found out it is indeed working, thanks for your reply!
