### ISSUE TITLE
Hardcoded window global

### ISSUE THREAD

**Issue by bisubus** [PillowPillow/ng2-webstorage#48]
Currently `window` global is hardcoded [here](https://github.com/PillowPillow/ng2-webstorage/blob/v1.6.2/lib/app.ts#L51). The check doesn't make much sense since this will throw type error in Node any way if `global.window` wasn't stubbed.

Probably should be

	if (typeof window !== 'undefined') {

**Comment by PillowPillow** [comment]
Fixed in the last version
