### ISSUE TITLE
localstorage variable not created for JSON stringified array

### ISSUE THREAD

**Issue by uzumakinaruto123** [PillowPillow/ng2-webstorage#5]
This works :-  

`this.storage.store('boundValue', 'hello');`

This doesn't :- 

`this.storage.store('boundValueabc', JSON.stringify(myjsonarray));`
`
console.log(JSON.stringify(myjsonarray));` this works.

**Comment by PillowPillow** [comment]
Hi, thanks for your report. I tried to reproduce your bug but it seems that is harder than i thought ^^. I created a branch #issue5 with a new unit test which you can watch . Please, tell me if it match with your code and otherwise update it. I would be happy to fix your problem.

**Comment by uzumakinaruto123** [comment]
@PillowPillow well i am not sure if the issue is related to this plugin. later i noticed , that console said `this is null`

```
normalFunction(){
     this.storage.store('boundValueabc', JSON.stringify(myjsonarray));  // works here

      return this._http.get('url')
        .map(this.extractData)
        .catch(this.handleError);
}
```


  ```
extractData(res: Response) {
    this.storage.store('boundValueabc', JSON.stringify(myjsonarray));  //doesn't work here. error -> this is null
  }
```

**Comment by PillowPillow** [comment]
Oh ok, it seems you have a dependency issue or a scope problem. I lock this issue for now, feel free to open another if you encounter a annoying behaviour with ng2webstorage.
best regards

**Comment by uzumakinaruto123** [comment]
yeah it was a scope problem. its not a plugin bug :+1:
