### ISSUE TITLE
Feature request -Have a method in service to check whether webStorage is supported and available

### ISSUE THREAD

**Issue by IevhenIkonnykov** [PillowPillow/ng2-webstorage#52]
It would be great if both services have a method to check whether sessionStorage/localStorage is supported and available. Such as `localStorageService.isSupported`.

**Comment by PillowPillow** [comment]
Added to the todo list, i'll add it soon.

**Comment by PillowPillow** [comment]
a method `isStorageAvailable` will be available with the next version.
