### ISSUE TITLE
Universal: local storage unavailable, Ng2Webstorage will use a fallback strategy instead

### ISSUE THREAD

**Issue by ennyta** [PillowPillow/ng2-webstorage#53]
When using in angular universal, I get the following error:
local storage unavailable, Ng2Webstorage will use a fallback strategy instead
and looks like the app breaks. 

Is there a support for server side rendering (universal)?

**Comment by PillowPillow** [comment]
Hi, currently the library doesn't support universal rendering. #50. I'm not against add it but i'm not familiar with this environment and i don't have the time right now to dig into it.
