### ISSUE TITLE
Custom configuration is ignored when decorators are used

### ISSUE THREAD

**Issue by esanzgar** [PillowPillow/ng2-webstorage#55]
Version: ngx-webstorage@1.8.0

I have configured ngx-webstorage to use a custom prefix and separator. 
`        Ng2Webstorage.forRoot({
            prefix: 'my_custom',
            separator: '.',
            caseSensitive: true
        }),
`
1. When I use the decorator like this:
`
@LocalStorage('test') private i:string;
`
Actual result:
`
ng2-webstorage|test = null
`
Expected result:
`
my_custom.test = null
`

2. When I use the decorator like this:
`
@LocalStorage('test', 'hello') private i:string;
`
Actual result:
`
ng2-webstorage|test = 'hello'
`
Expected result:
`
my_custom.test = 'hello'
`

3. When I use the decorator like this:
`
@LocalStorage('test') private i:string = 'hello;
`
Actual result:
`
ng2-webstorage|test = null
my_custom.test = 'hello'
`
Expected result:
`
my_custom.test = 'hello'
`

**Comment by owen26** [comment]
I'm having the same issue. It looks like something is wrong during the initialisation of this package. Default configurations been applied before custom configurations take effect.

**Comment by rhefner** [comment]
+1 Also seeing this issue.

**Comment by svitlychnyi** [comment]
Can someone check my pull request for this issue?

**Comment by PillowPillow** [comment]
fixed in dev, should be available with the next version tonight

**Comment by svitlychnyi** [comment]
@PillowPillow works like a charm :)
