### ISSUE TITLE
Inject services in others

### ISSUE THREAD

**Issue by phlex89** [PillowPillow/ng2-webstorage#57]
Is it possibile to use the LocalStorageService and SessionStorageService in my custom service?

I would like to create a wrapper for this services with some custom configuration but I can't inject them in my custom service. I think they are missing the `@Injectable()` decorator, right?

**Comment by rebendajirijr** [comment]
I'm facing the same issue.

**Comment by PillowPillow** [comment]
It should works out of the box, did you import the module? 
I m closing this issue for now, feel free to reopen if you still encounter this issue.
