### ISSUE TITLE
TypeError: Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by GeorgeKnap** [PillowPillow/ng2-webstorage#60]
when bundling `ngx-webstorage` version `1.8.0` with `webpack` & aot plugin for production, the minified script crash at runtime at this line:
`o=(n.n(i),"ng2-webstorage"),s="|",a=!1,l=(r={},r[i.STORAGE.local]="local",r[i.STORAGE.session]="session",r)`
![storage-problem](https://user-images.githubusercontent.com/11920691/29774152-c46936bc-8c00-11e7-986b-b98034d3a146.PNG)
![storage-error](https://user-images.githubusercontent.com/11920691/29774154-c581fe44-8c00-11e7-974d-e590fbc3b2b3.PNG)

 At development it all works normally. This is the non minified vendor script:
![webstorage_nonminified](https://user-images.githubusercontent.com/11920691/29774416-a5554eb8-8c01-11e7-93a4-85aa1518077c.PNG)

So the minified version has a problem with the STORAGE enum. 
Any thoughts about this?
Thanks

**Comment by GeorgeKnap** [comment]
I have found the problem. 
The `STORAGE` enum is being marked as pure by `@angular-devkit/build-optimizer` and thus removed from bundle.
this is the unminified code:
![pure](https://user-images.githubusercontent.com/11920691/29972124-4983407c-8f2b-11e7-85bf-4688bf1e7190.PNG)

**Comment by PillowPillow** [comment]
the version 3.x is a full rewrite of the library, i m closing this issue but feel free to create another one if you encounter a similar issue with the latest version of angular & ngx-webstorage.
