### ISSUE TITLE
How to set initial value other than the default

### ISSUE THREAD

**Issue by miliu99** [PillowPillow/ng2-webstorage#62]
say I have property called showMap. If I defined it like this

`@LocalStorage() showMap: boolean;
`
it works great. It remembers the setting before and after browser refresh.

However, if I want to showMap as default like this

`@LocalStorage() showMap: boolean = true;
`

It doesn't remember the setting before and after browser refresh. Instead, it always set showMap to true when I do browser refresh.

So, how do I set the default initial value?

**Comment by svitlychnyi** [comment]
you need to read the actual value from the localStorage instead of assigning it a true value.

**Comment by PillowPillow** [comment]
Nothing to add, @svitlychnyi  is right.
