### ISSUE TITLE
Featurerequest: Encoded storage

### ISSUE THREAD

**Issue by LProemer** [PillowPillow/ng2-webstorage#65]
I would prefer, if my localestorage where encoded. Not only for security, but also to increase space.

` storage.setItem(myKey, JSON.stringify({foo:"bar"});
 // stores: {"foo":"bar"}

 storage.setItem(myKey, encodeBase64(JSON.stringify({foo:"bar"}));
 // stores: eyJmb28iOiJiYXIifQ==  
`
Security is simple. Prevent the user from simple data manipulation. 

On the second hand, chrome Webstorage uses UTF16 for the WebStorage. 
To enhace Storagesize I propose to encode to UTF16 instead of UTF8. 

Of course base64 would be the simplest encryption. Thought probaply not the best for this job.

Optionally: Implement Interceptors so the Application can, if needed, get controll over how the data is stored.

**Comment by jonathanhecl** [comment]
I want this feature too :) I like it

**Comment by PillowPillow** [comment]
Hi, the version 3.x implements a concept of storage strategy. [ex for LocalStorage](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/strategies/localStorage.ts)([base class](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/strategies/baseSyncStorage.ts))

You can easily create your own strategy encoding & decoding the data the way you want. We event can 
consider adding the strategy directly in the library if you create a PR.

Regards
