### ISSUE TITLE
Having an empty string for prefix and separator causes infinite loop with @sessionStorage

### ISSUE THREAD

**Issue by JordanFriendshuh** [PillowPillow/ng2-webstorage#67]
I have recently switched to this library from bdv-angular2-localstorage since you guys use the same annotation patterns.  I didn't want our keys in session storage to change so I tried to set the prexfix and separator to "".  When I do this and try to use the session storage annotation I get a maximum call stack error.

**Comment by rjwijnen** [comment]
I am using:  Ng2Webstorage.forRoot({ prefix: '', separator: '', caseSensitive: true }) , and i don't get any errors in my applications.

**Comment by PillowPillow** [comment]
I m unable to reproduce this issue, please provide a sample repo.

**Comment by WindSaber** [comment]
I got the same issue

`Ng2Webstorage.forRoot({
      prefix: '',
      separator: '',
      caseSensitive: true
    })`

**Comment by WindSaber** [comment]
If somebody helps, I found another great repo where this and other problems are solved:

[https://github.com/zoomsphere/ngx-store](url)

**Comment by PillowPillow** [comment]
@WindSaber which version of angular and ngx-webstorage are you using?
