### ISSUE TITLE
Feature Request :  Object , Integer etc datatypes support

### ISSUE THREAD

**Issue by uzumakinaruto123** [PillowPillow/ng2-webstorage#7]
Is it possible to make syntax more easy ? By adding object , number etc support.

Like this Angular 1 localstorage plugin :-  
https://github.com/gsklee/ngStorage

There are no getters or setters. syntax is easy too.  Otherwise , plugin is great.

Thanks.

**Comment by PillowPillow** [comment]
Hello, can you explain a bit more about what you mean by adding the support of objects and numbers?
Currently, the plugin supports the storage of any data type.

**Comment by uzumakinaruto123** [comment]
you mean i can do this ? 

```
var MyObject = {'a': value , 'b' : value};
this.storage.store('boundValue', MyObject );
```

without stringifying ?

regarding syntax ,
instead of `this.storage.store('boundValue', MyObject );`  something like this can be easy `this.storage.boundValue= MyObject;`

**Comment by PillowPillow** [comment]
> you mean i can do this ?
> var MyObject = {'a': value , 'b' : value};
> this.storage.store('boundValue', MyObject );

sure, you don't have to stringify anything, the library handles all data types.

Concerning the syntax, I don't like it at all. With something like that you can't use fancy storage keys for a useless benefit.. 
Currently you can use the *store* and *retrieve* methods to avoid the observer or even use the decorators to basically have the same syntaxe than yours.

```typescript
@Injectable()
class FooBar {

	@LocalStorage('key')
	boundValue;

	constructor(private storageS:LocalStorageService) {}

	foo() {
		let val = {foo:1, bar:'2'};

		this.boundValue = val;
		// same as 
		this.storageS.store('key', val);

		console.log(this.boundValue.foo);
		//same as
		console.log(this.storageS.retrieve('key').foo);

	}
}
``

**Comment by uzumakinaruto123** [comment]
OK !  I was unaware about object storing without stringifying. About syntax its fine. Its your choice. I just made a feature req. :+1:   can be closed.

**Comment by PillowPillow** [comment]
that's my choice but I'm not the only one to use this library :). I understand your request but the benefits are realy poor compare to the needed dev and the naming flexibility.

The documentation wasn't clear enough about the typing?
