### ISSUE TITLE
Angular 5 compatability

### ISSUE THREAD

**Issue by Hopchenko** [PillowPillow/ng2-webstorage#73]
Hello, could you please update your awesome lib for supporting of angular 5.
Or you can easily merge https://github.com/PillowPillow/ng2-webstorage/pull/72
this pull request.
Best regards, Oleksii.

**Comment by nblavoie** [comment]
#72 has been merged into master.

**Comment by PillowPillow** [comment]
I m on it, it should be available during the night with some bug fixes.
