### ISSUE TITLE
can't run npm install ng2-webstorage@2.0.0

### ISSUE THREAD

**Issue by yooRabbit** [PillowPillow/ng2-webstorage#75]
I saw that release ng2-webstorage@2.0.0 has been publish,but still can't install for it?
Where should I update  ng2-webstorage?

**Comment by svitlychnyi** [comment]
@yooRabbit @PillowPillow The lib name has been changed too: "ngx-webstorage" (ng2 -> ngx)

**Comment by PillowPillow** [comment]
The name changed ~6months ago. But my bad, i forgot to deprecate the ng2.. npm repo.

**Comment by PillowPillow** [comment]
I deprecated the ng2-webstorage repo, but it seems that the message doesn't display on install at this moment. wait and see.
