### ISSUE TITLE
Error using Angular 4 on version 2.0 of ng2-webstorage

### ISSUE THREAD

**Issue by angeldaniel-adcm** [PillowPillow/ng2-webstorage#77]
I'm using angular 2 version 4.X.X and when I run ng serve I got this error:

ERROR in Error: Metadata version mismatch for module [app-route]/node_modules/ngx-webstorage/dist/app.d.ts, found version 4, expected 3, resolving symbol AppModule in [app-route]/src/app/app.module.ts, resolving symbol AppModule in [app-route]/src/app/app.module.ts, resolving symbol AppModule in [app-route]src/app/app.module.ts

I had to install the version 1.8 to fix this

**Comment by PillowPillow** [comment]
The v2 use the new angular compiler (as you can see in the package.json) you have to use the v1.8 if you wanna use ng4. 

Since i'm alone, it would be too much works for me to maintain multiple version in a same time so i decided to follow the angular versions as much as possible.
