### ISSUE TITLE
Error encountered resolving symbol values statically angular 5.0.3 and ngx-webstorage 2.0.1

### ISSUE THREAD

**Issue by lneninger** [PillowPillow/ng2-webstorage#82]
I'm using angular 5.0.3 and ngx-webstorage 2.0.1

Everyting went fine until I compiled using AOT. The folling error was thrown:

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in<app path>/node_modules/@angular/core/core.d.ts, resolving symbol Ng2Webstorage in <app path>/node_modules/ng2-webstorage/dist/app.d.ts, resolving symbol Ng2Webstorage in<app path>/node_modules/ng2-webstorage/dist/app.d.ts

**Comment by PillowPillow** [comment]
Hello, which version of the compiler are you using ? I'm using the library with the latest angular's version and everything works fine.

**Comment by lneninger** [comment]
Hi. I'm using "@angular/compiler": "5.0.3",

**Comment by lneninger** [comment]
**** @angular/compiler 5.0.3**

**Comment by lneninger** [comment]
It's working. I had a upper package.json that took control of node_modules selection. I removed it.

Thanks. Your question put me on the right path.
