### ISSUE TITLE
Version 2.0.1 does not exist in npm

### ISSUE THREAD

**Issue by niccolascosta** [PillowPillow/ng2-webstorage#84]
Version 2.0.1 not exist in npm repository.

**Comment by PillowPillow** [comment]
Hi, which npm repository are you using, [ng2-webstorage](https://www.npmjs.com/package/ng2-webstorage) is deprecated since many monthes. 
You have to use the new repository [ngx-webstorage](https://www.npmjs.com/package/ngx-webstorage)

**Comment by niccolascosta** [comment]
ok
