### ISSUE TITLE
Support String/Non-JSON (or JSON parsable) values

### ISSUE THREAD

**Issue by vivek4k** [PillowPillow/ng2-webstorage#88]
Error when retrieving string values stored in localStorage/sessionStorage due to [this code](https://github.com/PillowPillow/ng2-webstorage/blob/81f4d25c997bb898473aacb28ad7b1e03b6ef41f/lib/helpers/webStorage.ts#L30).

Do `JSON.parse` only when applicable and return value value without parsing when parsing fail

**Comment by PillowPillow** [comment]
Hi, i m against this feature for global usages. The local & session storages shouldn't hold non-json parsable values as we just have to add quotes around string values to be compliant..
If you really need this feature you can implement your own strategy and override the existing ones like i do in [this unit test](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/module.spec.ts)

regards
