### ISSUE TITLE
Support for Angular RC5/6

### ISSUE THREAD

**Issue by emanuelet** [PillowPillow/ng2-webstorage#9]
Is it possible to update the library to support the latest 2 RC of Angular 2?

**Comment by uzumakinaruto123** [comment]
It would be great if it supports final release version of angular. Angular 2.0.0

**Comment by uzumakinaruto123** [comment]
Any time estimate ?

**Comment by PillowPillow** [comment]
Sorry, i was very busy the last three weeks, i m on it.

**Comment by PillowPillow** [comment]
Hi, the last version is now available. my apologies for the delay.

**Comment by uzumakinaruto123** [comment]
you dont need to say sorry :p  its open source :D   well , thanks for the update.  appreciate  👍
