### ISSUE TITLE
Compatibility with Angular 6

### ISSUE THREAD

**Issue by wojofe** [PillowPillow/ng2-webstorage#90]
While linking dependencies I get 
`[ERROR] warning " > ngx-webstorage@2.0.1" has incorrect peer dependency "@angular/core@^5.0.0".`

**Comment by MardariG** [comment]
Is this library abandoned?

**Comment by e01010100** [comment]
This library does feel abandoned. Does anyone know any good forks or alternatives to it? I really like the convenience and conciseness this library offers.

**Comment by zeevkatz** [comment]
@e01010100 [https://github.com/PillowPillow/ng2-webstorage/pull/91#issuecomment-408764092](url)

**Comment by PillowPillow** [comment]
Hi, the version **2.x** supports the **angular 5 & 6**, the version **3.x** handles **angular7+**.

I was really busy with my company and didn't had the time to update this library (even if i m using it in my main company application). the lib's not dead, i assure you :). 

Regards
