### ISSUE TITLE
Way to disable caching or do manual refresh

### ISSUE THREAD

**Issue by sconix** [PillowPillow/ng2-webstorage#92]
We have a use case where the cache is causing a potential issue when same data change quickly in two tabs. In this rare case the data can get corrupted since the cache is giving old data. I understand the reason why the cache is there as commented in the old closed issue about the similar matter, but for example in our situation we are using the localstorage from service that already optimizes the writes / reads so having config option to turn off the caching would be really nice. Also just exposing the refresh method through the WebStorageService would also be sufficient.

**Comment by PillowPillow** [comment]
Hi, the version 3 of this library is a complete rewrite. It's allowing you to override the strategies used internally to interract with the local, session & in memory storage by using the multi provider [STORAGE_STRATEGIES](https://github.com/PillowPillow/ng2-webstorage/blob/9f3bb571a71aa629c5f7d856cc2cc2ae9df2a8e6/projects/ngx-webstorage/src/lib/strategies/index.ts#L7).
You can also directly interact with the internal cache by using the service [StrategyCache](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/core/strategyCache.ts). [example of usage](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/strategies/localStorage.ts)

Regards
