### ISSUE TITLE
LocalStorageService() constructor @ v3.0.0-beta.11

### ISSUE THREAD

**Issue by mixalistzikas** [PillowPillow/ng2-webstorage#96]
In the previous version I could run this code inside a module.

`const lsc = new LocalStorageService();`
`console.log(lsc.retrieve("token"));`

In this version v3.0.0-beta.11, as I can see, LocalStorageService() needs a parameter to constructor.

What param needs to be passed in this version?

**Comment by PillowPillow** [comment]
Hi @mixalistzikas , why do you wanna instantiate a new *LocalStorageService* ? A module, like a component or a simple Injectable can inject services through its constructor.

````typescript
@NgModule({...})
class MyModule {
    constructor(protected storage:LocalStorageService) {
        console.log(storage.retrieve('token'));
    }
}
````

In the other hand, if you REALLY need to instantiate a new *LocalStorageService*, i recommands you to look at [the service declaration](https://github.com/PillowPillow/ng2-webstorage/blob/271d2dda40158d2d543297a3f914a3a3f7183ed0/projects/ngx-webstorage/src/lib/services/localStorage.ts#L9).
As you can see, the service needs an object that implements the [StorageStrategyInterface](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/core/interfaces/storageStrategy.ts). For the LocalStorageService case, the library uses by the hood [this strategy](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/strategies/localStorage.ts).

**Comment by mixalistzikas** [comment]
const lsc = new LocalStorageService();
    const DEFAULT_DROPZONE_CONFIG: DropzoneConfigInterface = {
    headers: {
        "Authorization": `Bearer ${lsc.retrieve("token")}`
    }
    };

    @NgModule({
        imports: [
           SharedModule,
           CommonModule
       ],
       providers: [
        {
            provide: DROPZONE_CONFIG,
            useValue: DEFAULT_DROPZONE_CONFIG
        }
    ]
    })
    export class HotelsModule {
    }

that's the code I'm trying to implement

**Comment by PillowPillow** [comment]
As far i can see you can achieve what you want by using the provider's useFactory method
````typescript
@NgModule({
	imports: [
		SharedModule,
		CommonModule
	],
	providers: [

		{
			provide: DROPZONE_CONFIG,
			useFactory: (storage:LocalStorageService):DropzoneConfigInterface => ({
				"Authorization": `Bearer ${lsc.retrieve("token")}`
			}),
			deps: [LocalStorageService]
		}
	]
})
export class HotelsModule {
}
````
The code above should works as you wish
