### ISSUE TITLE
Unit tests with Decorators

### ISSUE THREAD

**Issue by Darkein** [PillowPillow/ng2-webstorage#97]
Hello,

I'm using sesssionStorage decorator inside a service which I want to test.

Because i'm using jest for testing, I don't have access to SessionStorage. Can I mock the sessionStorage to use InMemoryStorage instead?

I tried to inspire myself with your tests, but nothing worked ( I always have `ReferenceError: Storage is not defined`)

Thanks for your help

**Comment by PillowPillow** [comment]
Hi @Darkein, sure you can. 
You just have to define a strategyStub overriding the SessionStorageStrategy like i do [here](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/module.spec.ts) for the localStorage.

The strategy indexer will take the last strategy defined for the for a given type (in your case [session_storage](https://github.com/PillowPillow/ng2-webstorage/blob/271d2dda40158d2d543297a3f914a3a3f7183ed0/projects/ngx-webstorage/src/lib/constants/strategy.ts#L3))

You can define a stub class implementing the [StorageStrategy](https://github.com/PillowPillow/ng2-webstorage/blob/271d2dda40158d2d543297a3f914a3a3f7183ed0/projects/ngx-webstorage/src/lib/core/interfaces/storageStrategy.ts#L3) interface or use the StorageStrategyStub that i m exposing as helper.

[StorageStrategyStub](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/stubs/storageStrategy.stub.ts) is a class for test only purpose. It allow to define the strategyName at instantiation. By using an existing name and declaring the new strategy with the multi provider you can overriding the existing one.

Regards

**Comment by Darkein** [comment]
Hello @PillowPillow , thanks for your answers. 

Unfortunately It doesn't work. I tried to debug my tests and it seems `NgxWebstorageModule.forRoot()` try to instanciate `LocalStorageStrategy `which try to inject `LOCAL_STORAGE`, even if I don't use them. I will try to mock them before mocking sessionStorageStrategy.

I keep you in touch :)

**Comment by PillowPillow** [comment]
mmh interesting, I m not using jest but it shouldn't throw any error if [LOCAL_STORAGE & SESSION_STORAGE](https://github.com/PillowPillow/ng2-webstorage/blob/master/projects/ngx-webstorage/src/lib/core/nativeStorage.ts). Moreover i m checking if window exists before doing anything in order to handle server side usage.

Can you show me the complete stacktrace ? Or event better provide me an ultra basic repo that i could use to debug that?

**Comment by Darkein** [comment]
Hum, I can't mock LOCAL_STORAGE because it's injected in the import. I will not have time to create a repo right now, but I can send you the (horrible) [stack trace](https://gist.github.com/Darkein/9fd94e2bd9f6c2b1d95575843c905070#file-stacktrace-js).

```
ReferenceError: Storage is not defined
    at LocalStorageStrategy.ctorParameters (**\node_modules\ngx-webstorage\bundles\ng:\ngx-webstorage\lib\strategies\localStorage.ts:12:56)
```

**Comment by PillowPillow** [comment]
mmh, which version of typescript are you using. As far i can see, the error come from the type that i'm using in the [strategy construtor](https://github.com/PillowPillow/ng2-webstorage/blob/9f3bb571a71aa629c5f7d856cc2cc2ae9df2a8e6/projects/ngx-webstorage/src/lib/strategies/localStorage.ts#L12) - Storage which come from the typescript's **lib.dom** file.
I can try to remove its usages and deploy a new version.

**Comment by PillowPillow** [comment]
I deployed a new version 3.0.0-beta.12 removing the typescript's Storage interface usage. Can you remove your LOCAL_STORAGE & SESSION_STORAGE overriding from your test file and tell me if it works?

> Hum, I can't mock LOCAL_STORAGE because it's injected in the import. 
The providers defined in the current module are always have the priority over the library ones.

**Comment by Darkein** [comment]
Wow, well played, it's working !

Thanks a lot :)

PS: I'm using typescript 3.1.3.
