### ISSUE TITLE
LocalStorageService - Observe changes in another is not working

### ISSUE THREAD

**Issue by joterr** [PillowPillow/ng2-webstorage#98]
**Describe the bug**
Using the latest version 3.0.0-beta.12 (also testet with 3.0.0-beta.11) it is not possible to observe changes from other windows. I've tested the LocalStorageService.observe method in both ways - with two windows and just one window. The event ist only fired The event only gets fired if it's just a window. I've used this lib in both windows to set the local storage.

**To Reproduce**
1. Implement observe example from README with a specific key.
2. Set LocalStorage with the same key in another window with the same origin.

**Expected behavior**
The observe method should emit a change. Observing localStorage should work across multiple windows (like it did before).

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome, FF, Opera
 - Version 70.0.3538.77, 63.0.1, 56.0.3051.52

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 8.0
 - Browser FF
 - Version 62.0.3

**Comment by PillowPillow** [comment]
Hello, thanks for your feedback. 
The version 3.0.0-beta.13 should fix you issue.

regards

**Comment by joterr** [comment]
Nice one! It's working again - thank you.
