### ISSUE TITLE
Error: Cannot read property reverse of null

### ISSUE THREAD

**Issue by asaph26** [PillowPillow/ng2-webstorage#99]
**Versions (please complete the following information):**
 - NgxWebstorage: [e.g. 3.0.0-beta.13]
 - Angular: [e.g. 7.0.4]

**Describe the bug**
Error: Cannot read property reverse of null.
https://github.com/PillowPillow/ng2-webstorage/blob/02f829dd568c693554c303bf77ac391dfb7bcd4b/projects/ngx-webstorage/src/lib/services/strategyIndex.ts#L16-L17

The following line needs to be updated to use `this.strategies` instead of using the strategies local variable which can be null and is handled.

**Expected behavior**
No error to occur

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

UPDATE: This issue is solved by including the forRoot() method on the root level.

**Comment by PillowPillow** [comment]
Hello, thanks for your feedback. 
Even if your error came from the usage of forRoot, it was a bug too, the library shouldn't crash. 
The v3.0.14 fixed that.

regards,
